### ISSUE TITLE
Fix flaky //ros2/test/diagnostics:diagnostic_heartbeat_test

### ISSUE THREAD

**Issue by mvukov** [mvukov/rules_ros2#195]

**Comment by ahans** [comment]
@mvukov are you already in this? If not, I can have a look. I guess we could fix this by using reliable communication and replacing the recorder by a subscriber node in the test.

**Comment by mvukov** [comment]
Hi Alex, I saw a couple of failures of this test recently and wanted to make a note here. If you have some time, please go ahead. I do the same: replace the recorder with a subscriber.
