### ISSUE TITLE
Error importing messages different than std_msg

### ISSUE THREAD

**Issue by Sanjaer** [mvukov/rules_ros2#5]
Hi, inside std_msgs there is another folder called detail, that contains the header_struct msg among several others. 

For my project I'm using nav_msgs, so I've added rules to build nav_msgs and geometry_msgs (as it depended on them) but now I'm facing this error:
```

In file included from bazel-out/k8-fastbuild/bin/external/ros2_common_interfaces/cpp_geometry_msgs_cpp/geometry_msgs/msg/accel_with_covariance_stamped__type_support.cpp:7:
bazel-out/k8-fastbuild/bin/external/ros2_common_interfaces/cpp_geometry_msgs_cpp/geometry_msgs/msg/detail/accel_with_covariance_stamped__struct.hpp:19:10: fatal error: std_msgs/msg/detail/header__struct.hpp: No such file or directory
   19 | #include "std_msgs/msg/detail/header__struct.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I think maybe this block inside common_interfaces.BUILD.bazel isn't accounting for subfolders inside std_msgs?
```
ros2_interface_library(
    name = "std_msgs",
    srcs = glob(["std_msgs/msg/*.msg"]),
    deps = ["@ros2_rcl_interfaces//:builtin_interfaces"],
    visibility = ["//visibility:public"],
)
```
thanks in advance!

**Comment by mvukov** [comment]
Hi Pablo,

Unlike ROS1 genmsg that requires deps to be correctly set up, ROS2 doesn't require this (or I didn't set it up correctly yet). Therefore, if deps aren't correct, you'll only see that in C/C++ compilation stage.

I added handling of geometry_msgs and nav_msgs in 3510f62378e520c07c5c4d8d04ba20268d43edec.
